=== Graphics, Mouse

==== Get Mouse Pointer coordinates (Window) 'MouseEvent'
For the HALCON code below the function returns the location of the mouse pointer relative to the windows coordinates (row and column) of the pixels covered by the window. The button pressed on the mouse is calculated using a binary code system that once added up reveals all the numbers that wer pressed. The final value is returned to the 'Button' variable. This is also true for the 'sub_pix' variation but that returns the values with sub pixel accuracy.


HALCON:
[,hdevelop]
----
get_mbutton( : : WindowHandle : Row, Column, Button)
get_mbutton_sub_pix( : : WindowHandle : Row, Column, Button)
----

In PCL there is a class for this called 'MouseEvent'. This class captures the mouse location on the window, the button pressed and also captures certain keys on teh keyboard to assess for 'special' commands. 
MouseEvent class saves the following inputs:
 	- type   			Event type (Pressed or Released)
 	- button 			The Button that causes the event
	- x      			X position of mouse pointer at that time where event got fired
	- y      			Y position of mouse pointer at that time where event got fired
 	- alt    			Whether the ALT key was pressed at that time where event got fired
 	- ctrl   			Whether the CTRL key was pressed at that time where event got fired
 	- shift  			Whether the Shift key was pressed at that time where event got fired
 	- selection_mode 	Whether we are in selection mode

To aquire this information within the window you will need to implement the following code in the PCLVisualizer containing your cloud point data.

PCL: 
[,cpp]
----
#include <pcl/visualization/keyboard_event.h> 
// Example Visualisation function
pcl::visualization::PCLVisualizer::Ptr viewer (new pcl::visualization::PCLVisualizer ("3D Viewer"));
viewer->registerMouseCallback (mouseEventOccured, (void*)&viewer);

void mouseEventOccured (const pcl::visualization::MouseEvent &event, void* viewer_void)
{
	// In this section you are able to recall the class 'MouseEvent' using the getters below. 
	std::cout << event.getType() << std::endl; 					//Displays the Event Type to terminal
	std::cout << event.getButton() << std::endl;				//Displays the Button that caused event to terminal
	std::cout << event.getX() << std::endl;						//Displays the X coordinate to terminal
	std::cout << event.getY() << std::endl;						//Displays the Y coordinate to terminal
	std::cout << event.getKeyboardModifiers() << std::endl;		//Displays the Keyboard keys pressed to terminal
	std::cout << event.getSelectionMode() << std::endl;			//Displays the selection mode to terminal
}	
----

==== Selecting Areas or Multiple Points
For selecting areas and points in a Point Cloud viewer there must be a selected mouse callback function ot register the input from the user.
The mouse naturally drags and orientates the image when the M1 button is clicked. To register a mouse callback with a specific function you can use the above function with specified additions.
To search for a mouse input option such as the 'alt' key.
Following this you must decide what to do with the data once selected. This can be to copy the selected points or to adjust the colour using the coding options detailed in Graphics Visualisations of this document.


PCL:
[,cpp]
----
boost::signals2::connection pcl::visualization::PCLVisualizer::registerPointPickingCallback (std::function< void(const pcl::visualization::PointPickingEvent &)> cb	) ;	
// Where cb is the CallBack function 
----

PCL:
[,cpp]
----
// ALSO
// Under the class PointPickingEvent
#include <pcl/pcl_macros.h>
#include <pcl/types.h> // for pcl::indices
viewer->registerPointPickingCallback (performPointPick,(void*)&viewer)

void performPointPick()
{
	getPointIndex(idx_);
	[x,y,z] = getPoint(float &x, float &y, float &z) const;	
	std::cout << "Point Picked Location: " + idx_ << std::endl;
	// displays the point index for point data.
	std::cout << getPoint(float &x, float &y, float &z) const;	
	// displays the point coordinates for point.
}
----


==== Selecting single Points
Similar rules apply as the Selecting areas section.
PCL:
[,cpp]
----
boost::signals2::connection pcl::visualization::PCLVisualizer::registerPointPickingCallback (std::function< void(const pcl::visualization::PointPickingEvent &)> cb) 	
// Where cb is the CallBack function 

// ALSO 
// Under the class PointPickingEvent
#include <pcl/pcl_macros.h>
#include <pcl/types.h> // for pcl::indices
viewer->registerPointPickingCallback (performAreaPick,(void*)&viewer)

void performAreaPick()
----


==== Double Click
In HALCON there is a function that allows for a double click to be registered on the window. This capability is not yet seen in the visualizer window for PCL. However they have allowed for certain keyboard inputs to be registered by the mouse event as well. These options can be seen above.

HALCON:
[,hdevelop]
----
send_mouse_double_click_event( : : WindowHandle, Row, Column, Button : Processed)
----

==== Drag Event

HALCON:
[,hdevelop]
----
send_mouse_drag_event( : : WindowHandle, Row, Column, Button : Processed)
----

PCL does not have an available drag event for personal adjustment, the current drag movement on the window allows for the point cloud data to be rotated and pivoted throughout the viewer.

This mouse button event sends the position of the mouse in the window to the 'WindowHandle' and this signals the 'Button' has been released. The 'Button' is a previously coded mouse event. See Mouse Event for more details.

==== Send Mouse Up/Down Event 

HALCON:
[,hdevelop]
----
send_mouse_up_event( : : WindowHandle, Row, Column, Button : Processed)
send_mouse_down_event( : : WindowHandle, Row, Column, Button : Processed)
----

The send mouse up and down event in halcon is similiar to the PCL get.point caller for PCL. It takes the pointers location from the window and states the current position in the window or function specified.

PCL:
[,cpp]
----
	std::cout << event.getX() << std::endl;						//Displays the X coordinate to terminal
	std::cout << event.getY() << std::endl;						//Displays the Y coordinate to terminal
----




