== Graphics, Mouse

HALCON:

[,hdevelop]
---
get_mbutton( : : WindowHandle : Row, Column, Button)
---

PCL: 
[,cpp]
---
pcl::visualisation::PointPickingCallback::performAreaPick()
---


HALCON:

[,hdevelop]
---
get_mbutton_sub_pix( : : WindowHandle : Row, Column, Button)
---

PCL: 
[,cpp]
---
pcl::visualisation:: (TODO)
---


HALCON:
---
get_mposition( : : WindowHandle : Row, Column, Button)
---

PCL:



HALCON:

[,hdevelop]
---
get_mposition_sub_pix( : : WindowHandle : Row, Column, Button)
---

PCL:
[,cpp]
---

---

HALCON:

[,hdevelop]
---
getmshape( : : WindowHandle : Cursor)
---

PCL:
[,cpp]
---

---

HALCON:

[,hdevelop]
---
query_mshape( : : WindowHandle : ShapeNames)
---

PCL:
[,cpp]
---

---


HALCON:

[,hdevelop]
---
send_mouse_double_click_event( : : WindowHandle, Row, Column, Button : Processed)
---

PCL:
[,cpp]
---

---


HALCON:

[,hdevelop]
---
send_mouse_down_event( : : WindowHandle, Row, Column, Button : Processed)
---

PCL:
[,cpp]
---

---


HALCON:

[,hdevelop]
---
send_mouse_drag_event( : : WindowHandle, Row, Column, Button : Processed)
---

PCL:
[,cpp]
---

---


HALCON:

[,hdevelop]
---
send_mouse_up_event( : : WindowHandle, Row, Column, Button : Processed)
---

PCL:
[,cpp]
---

---


HALCON:

[,hdevelop]
---
set_mshape( : : WindowHandle, Cursor : )
---

PCL:
[,cpp]
---

---




